// 1. Core Atomic Skeleton Primitives
export * from "./Skeleton"
export * from "./SkeletonText"
export * from "./SkeletonHeading"
export * from "./SkeletonParagraph"
export * from "./SkeletonAvatar"
export * from "./SkeletonImage"
export * from "./SkeletonIcon"
export * from "./SkeletonButton"
export * from "./SkeletonBadge"
export * from "./SkeletonInput"
export * from "./SkeletonCard"
export * from "./SkeletonDivider"

// 2. Domain-Specific Modular Skeletons
export * from "./navigation"
export * from "./search"
export * from "./hero"
export * from "./courses"
export * from "./catalog"
export * from "./pathways"
export * from "./roadmap"
export * from "./simulator"
export * from "./dsa"
export * from "./lesson"
export * from "./dashboard"
export * from "./certificates"
export * from "./jobs"
export * from "./hackathons"
export * from "./ats"
export * from "./ai"
export * from "./profile"
export * from "./analytics"
export * from "./common"
